---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 20 seconds for target connection to become reachable/usable."
      pause:
        seconds: 20

    - name: "Update repos"
      become: yes
      apt:
        update_cache: yes

    - name: "Upgrade distribution"
      become: yes
      apt:
        upgrade: dist

    - name: "install python for Ansible."
      become: yes
      apt:
        name: python3

  roles:
    - configure-prometheus-node-exporter
    - configure-server