- name: "Install nodejs"
  become: yes
  shell: curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
  args:
    warn: no

- name: "Install nodejs"
  become: yes
  apt:
    name: nodejs
    update_cache: yes

- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    production: yes
    state: present
    global: yes

- name: "Copy and unpack backend"
  unarchive:
    src: "files/backend.tar.gz"
    dest: "."

- name: Install packages for backend
  npm:
    path: ~/backend

- name: Build backend
  command: npm run build
  args:
    chdir: ~/backend

- name: Executing backend
  shell: |
    pm2 start ~/backend/dist/main.js