- name: "Install nodejs"
  shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
  args:
    warn: no

- name: "Install nodejs"
  apt:
    name: nodejs
    update_cache: yes

- name: "Install pm2"
  npm:
    name: pm2
    state: latest
    global: yes